on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SBOM_Generate_Action
    permissions:
      contents: read
    steps:
     - name: Set up GCS credentials
       run: echo "${{ secrets.GCS_CRDENTIALS }}" > gcs-credentials.json
     - name: HashiCorp - Setup Terraform
       # You may pin to the exact commit or the version.
       # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
       uses: hashicorp/setup-terraform@v2.0.3
     - name: Terraform init Verify
       run : terraform init
     - name: SBOM Generation Step
       id: sbom_generator
       uses: sanyam803/hello-world-javascript-action@v5.5
       with:
          gcs_credentials: ${{ secrets.GCS_CRDENTIALS }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          owner : 'sanyam803'
          repoName : 'Neural-Image-Synthesis'
          
       
