on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SBOM_Generate_Action
    permissions:
      contents: read
    steps:
     - name: Set up GCS credentials
       run: echo "${{ secrets.GCS_CRDENTIALS }}" > gcs-credentials.json
     - name: SBOM Generation Step
       id: sbom_generator
       uses: sanyam803/hello-world-javascript-action@v4.8
       with:
          gcs_credentials: ${{ secrets.GCS_CRDENTIALS }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
       
