on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SBOM_Generate_Action
    permissions:
      contents: read
    steps:
     - name: Set up GCS credentials
       run: echo "${{ secrets.GCS_CRDENTIALS }}" > gcs-credentials.json
     - name: HashiCorp - Setup Terraform
       # You may pin to the exact commit or the version.
       # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
       uses: hashicorp/setup-terraform@v2.0.3
     - name: Terraform init Verify
       run : terraform init 
     - name: Terraform Plan Generation  
       run : terraform plan -var-file=../environments/non-prod/terraform.tfvars
     - name: IAC Validtion Step
       id: validate_iac
       uses: sanyam803/SCC-Left-Shift-Security@v1.1
       with:
          gcs_credentials: ${{ secrets.GCS_CRDENTIALS }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          planFilePath: "IAC/myplanFile.plan"
          sarifFilePath: "/"
          
          
       
