on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
     - name: Set up GCS credentials
       run: echo "${{ secrets.GCS_CRDENTIALS }}" > gcs-credentials.json
     - name: Install OSV scanner
       run: |
          # Install the OSV scanner
          curl -fsSL https://pkg.osv.dev/install.sh | sh
     - name: Hello world action step
       id: hello
       uses: sanyam803/hello-world-javascript-action@v1.2
       
