on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SBOM_Generate_Action
    permissions:
      contents: read
      pull-requests: write
    steps:
     - name: Set up GCS credentials
       run: echo "${{ secrets.GCS_CRDENTIALS }}" > gcs-credentials.json
     - name: Install OSV scanner
       run: |
          # Install the OSV scanner
          curl -fsSL https://pkg.osv.dev/install.sh | sh
     - name: SBOM Generation Step
       id: sbom_generator
       uses: sanyam803/hello-world-javascript-action@v5.0
       with:
          gcs_credentials: ${{ secrets.GCS_CRDENTIALS }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
       
